### ISSUE TITLE
set duration of alert

### ISSUE THREAD

**Issue by pprevalon** [trilliwon/JDropDownAlert#14]
are there anyways to set the duration of the alert instead of showing then dissappear

**Comment by trilliwon** [comment]
You can change the initial value of **delay** property in JDropDownAlert class.

**Comment by pprevalon** [comment]
work great, thanks

**Comment by Dudi00** [comment]
@pprevalon in my fork there you can do it for each particular alert.

**Comment by trilliwon** [comment]
@Dudi00 Yes, Of course

**Comment by trilliwon** [comment]
https://github.com/trilliwon/JDropDownAlert/pull/15
