### ISSUE TITLE
Is it possible to change Title color ?

### ISSUE THREAD

**Issue by X901** [trilliwon/JDropDownAlert#18]
Hi ,
Is it possible to add different colors for Title and Message ?
What I mean for example 
change Title color to Black
and message color to White

**Comment by trilliwon** [comment]
Hi, now changing title and message label color separately is not possible.
If you need, I will make it possible.

**Comment by X901** [comment]
It will be great to have it , Thank you

**Comment by trilliwon** [comment]
Now It's available with version 1.0.2. Thanks.
