### ISSUE TITLE
Could you add boolean to dismiss alert

### ISSUE THREAD

**Issue by perlasivakrishna** [trilliwon/JDropDownAlert#22]
I had case where i want to keep the alert until user responds to it or swipes. So I would like you to maintain a boolean value to dismiss based on delay  otherwise it should dismiss until we removed..

At present alert is dismissing after delay time

**Comment by trilliwon** [comment]
@perlasivakrishna 

You can set delay time very long and then instead of boolean value just call ```viewDidTap()```.
